#!/bin/bash

set -e

if [ -z "$TRI_CMD" ]; then
    SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
    ROOT_DIR="$(dirname "$SCRIPT_DIR")"
    export TRI_CMD="$ROOT_DIR/tri-pp"
fi

DIR="$1"
shift

ANSWER_SUFFIX="$1"
shift

[ -d "$DIR" ] || exit 1

echo -n "$DIR ($@) ... "

export TIMEFORMAT="%U"
# Capture both stdout and stderr (2>&1) as in example
TIME=`time ( cd $DIR; ./runtests "$@" >Output"$ANSWER_SUFFIX" 2>&1; ) 2>&1`

res=0

# Color support
if [ -t 1 ] && [ -n "$TERM" ] && [ "$TERM" != "dumb" ]; then
    RED=`tput setaf 1`
    GREEN=`tput setaf 2`
    YELLOW=`tput setaf 3`
    RESET=`tput sgr0`
else
    RED=""
    GREEN=""
    YELLOW=""
    RESET=""
fi

if [ ! -f "$DIR"/Answers"$ANSWER_SUFFIX" ]; then
    echo -e "${RED}\tMissing Answers file!${RESET}"
    res=1
else
    if cmp -s "$DIR"/Answers"$ANSWER_SUFFIX" "$DIR"/Output"$ANSWER_SUFFIX"; then
        echo -ne "${GREEN}\tSucceeded${RESET}"
    else
        echo -e "${RED}\tFAILED${RESET}"
        echo
        diff "$DIR"/Answers"$ANSWER_SUFFIX" "$DIR"/Output"$ANSWER_SUFFIX" || true
        echo
        cp "$DIR"/Output"$ANSWER_SUFFIX" "$DIR"/Output"$ANSWER_SUFFIX"-"`date +%s`"
        res=1
    fi
fi

echo -n " ($TIME"
echo "s)"

exit $res
