#!/bin/sh

TESTS="typedef_removal.c \
       struct_multi_field.c \
       struct_single_line.c \
       struct_combined_fields.c \
       nested_struct.c \
       struct_array.c \
       struct_pointer.c \
       enum_typedef.c \
       basic_type_alias.c \
       multi_typedef.c \
       anonymous_struct_typedef.c"

# -Wno-everything mirrors how TriCera invokes tri-pp; newer clang otherwise
# promotes e.g. implicit-int (seen in intermediate rounds of the anonymous
# typedef test) to a hard error
for name in $TESTS; do
    echo
    echo $name
    $TRI_CMD "$@" $name -- -xc -Wno-everything 2>&1
done
