#!/bin/sh

TESTS="determinize.c \
       make_calls_unique.c \
       loop_rewrite.c \
       entry_function.c \
       no_decl_slice.c"

for name in $TESTS; do
    echo
    echo $name
    case $name in
        determinize.c) $TRI_CMD "$@" --determinize determinize.c -- -xc 2>&1 ;;
        make_calls_unique.c) $TRI_CMD "$@" --make-calls-unique make_calls_unique.c -- -xc 2>&1 ;;
        loop_rewrite.c) $TRI_CMD "$@" loop_rewrite.c -- -xc 2>&1 ;;
        entry_function.c) $TRI_CMD "$@" -m foo entry_function.c -- -xc 2>&1 ;;
        no_decl_slice.c) $TRI_CMD "$@" --no-decl-slice no_decl_slice.c -- -xc 2>&1 ;;
    esac
done
