name: Build

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-13]

    steps:
    - uses: actions/checkout@v4

    - name: Install libtool (macOS)
      if: runner.os == 'macOS'
      run: brew install libtool

    - name: Install libtool (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install libtool-bin

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: ./mk

    - name: Rename Binary
      run: mv ${{ github.workspace }}/build/tri-pp ${{ github.workspace }}/tri-pp-${{ matrix.os }}

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ github.workspace }}/tri-pp-${{ matrix.os }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
